public class InterviewRestResourcesTest {
/*    @isTest static void testGetFutureInterviewsRestResource() {
        ID recordId = TestFactory.CreateCaseRecord();
        RestRequest req = new RestRequest();
        req.requestURI = 'https://yourInstance.salesforce.com/services/apexrest/Cases/'+ recordId;
        req.httpMethod = 'GET';
        RestContext.request = req;
        // Call the method to test
        Case record = FeatureCaseManager.getCaseById();
        // Assert results
        System.assert(record != null);
        System.assertEquals('High', record.Priority);
    }

    @isTest static void testGetInterviewByIdRestResource() {
        ID recordId = TestFactory.CreateCaseRecord();
        RestRequest req = new RestRequest();
        req.requestURI = 'https://yourInstance.salesforce.com/services/apexrest/Cases/'+ recordId;
        req.httpMethod = 'GET';
        RestContext.request = req;
        // Call the method to test
        Case record = FeatureCaseManager.getCaseById();
        // Assert results
        System.assert(record != null);
        System.assertEquals('High', record.Priority);
    }
    
    @isTest static void testGetInterviewsByDateRangeRestResource() {
        ID recordId = TestFactory.CreateCaseRecord();
        RestRequest req = new RestRequest();
        req.requestURI = 'https://yourInstance.salesforce.com/services/apexrest/Cases/'+ recordId;
        req.httpMethod = 'GET';
        RestContext.request = req;
        // Call the method to test
        Case record = FeatureCaseManager.getCaseById();
        // Assert results
        System.assert(record != null);
        System.assertEquals('High', record.Priority);
    }
    */
    
}